# Generated by Django 4.2.5 on 2023-09-15 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='From',
            new_name='Form',
        ),
    ]
